# Generated by Django 5.2.17 on 2026-09-19 14:45

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('radius_km', models.FloatField(default=300.0, help_text='Risk radius in kilometres used by the Trigger Filter.', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('min_magnitude', models.FloatField(default=5.0, help_text='Minimum USGS magnitude that activates the call tree here.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('evacuation_instruction', models.TextField(blank=True, help_text='Location-specific guidance appended to every alert (assembly point, stairwell, floor warden).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeismicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usgs_id', models.CharField(help_text='USGS event id; the idempotency key for repeated feed reads.', max_length=64, unique=True)),
                ('magnitude', models.FloatField()),
                ('place', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth_km', models.FloatField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('usgs_feed', 'USGS GeoJSON feed'), ('usgs_webhook', 'USGS ENS webhook'), ('usgs_email', 'USGS ENS email alert'), ('manual', 'Manual / simulated')], default='usgs_feed', max_length=20)),
                ('detail_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('triggered', models.BooleanField(default=False, help_text='Whether the Trigger Filter activated a call tree.')),
                ('evaluation_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target', models.CharField(blank=True, max_length=160)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('drill', 'Scheduled drill'), ('incident', 'Live seismic incident'), ('test', 'System test')], default='drill', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual (Safety Officer)'), ('automatic', 'Automatic (USGS trigger)')], default='manual', max_length=16)),
                ('message_template', models.TextField(blank=True, help_text='Alert body. Placeholders: {name}, {location}, {magnitude}, {place}, {instruction}, {link}.')),
                ('response_window_minutes', models.PositiveIntegerField(default=5, help_text='Compliance window. Non-responders are flagged after this.')),
                ('reminder_interval_minutes', models.PositiveIntegerField(default=2)),
                ('max_reminders', models.PositiveSmallIntegerField(default=2)),
                ('send_sms', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_drills', to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(related_name='drills', to='core.location')),
                ('seismic_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drills', to='core.seismicevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(help_text='Mobile number in E.164 form, e.g. +639171234567.', max_length=20)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(choices=[('staff', 'DSO Staff'), ('floor_warden', 'Floor Warden'), ('emt', 'Emergency Management Team'), ('safety_officer', 'Safety Officer')], default='staff', max_length=20)),
                ('escalation_tier', models.PositiveSmallIntegerField(default=1)),
                ('sms_opt_in', models.BooleanField(default=True)),
                ('email_opt_in', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='core.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.location')),
            ],
            options={
                'ordering': ['escalation_tier', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='DrillParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting response'), ('notified', 'Alert delivered'), ('safe', 'Safe'), ('help', 'Needs help'), ('unreachable', 'Unreachable'), ('non_compliant', 'Non-compliant')], db_index=True, default='pending', max_length=16)),
                ('status_token', models.CharField(default=core.models.new_token, max_length=64, unique=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_channel', models.CharField(blank=True, max_length=16)),
                ('response_text', models.CharField(blank=True, max_length=255)),
                ('reminders_sent', models.PositiveSmallIntegerField(default=0)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.drill')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.employee')),
            ],
            options={
                'ordering': ['employee__escalation_tier', 'employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(db_index=True, max_length=32)),
                ('text', models.CharField(max_length=500)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('process_note', models.CharField(blank=True, max_length=255)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='core.drillparticipant')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS (M360)'), ('email', 'Email (SMTP)')], max_length=10)),
                ('purpose', models.CharField(choices=[('initial', 'Initial alert'), ('reminder', 'Reminder'), ('escalation', 'EMT escalation'), ('all_clear', 'All clear')], default='initial', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.drillparticipant')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='drillparticipant',
            index=models.Index(fields=['drill', 'status'], name='core_drillp_drill_i_cc7770_idx'),
        ),
        migrations.AddConstraint(
            model_name='drillparticipant',
            constraint=models.UniqueConstraint(fields=('drill', 'employee'), name='unique_participant_per_drill'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['location', 'is_active'], name='core_employ_locatio_5a7cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['participant', 'channel'], name='core_notifi_partici_3ed675_idx'),
        ),
    ]
