# Generated by Django 5.2.17 on 2026-09-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email (SMTP)')], max_length=10),
        ),
    ]
